name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: lint
        run: |
          for file in $(find . -name "*.php"); do
            php -l $file
          done

  build:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t junia:latest .


